#Cumulative Summation

In [2]:
import numpy as np
student_marks = np.array([50, 60, 80,75])
print(student_marks)

[50 60 80 75]


In [3]:
np.cumsum(student_marks)

array([ 50, 110, 190, 265])

In [4]:
print(student_marks)

[50 60 80 75]


In [5]:
np.sum(student_marks)

265

In [6]:
np.sum([50,70,80])

200

Multi Dimensional Array

In [10]:
# U6 means Unicode String in Bytes
np.array(["Sachin", "Rahul"])

array(['Sachin', 'Rahul'], dtype='<U6')

In [14]:
student_marks = np.array([[20,30,40], [10,20,30],[40,50,65]])

In [15]:
print(student_marks)

[[20 30 40]
 [10 20 30]
 [40 50 65]]


In [16]:
student_marks

array([[20, 30, 40],
       [10, 20, 30],
       [40, 50, 65]])

In [17]:
student_marks[student_marks>40]

array([50, 65])

In [18]:
student_marks>40


array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [19]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
result = arr[mask]
print(result)

[3 4 5]


In [20]:
mask

array([False, False,  True,  True,  True])

In [21]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
indices = np.array([0, 2])
result = arr[indices, :]
print(result)

[[1 2]
 [5 6]]


In [22]:
student_marks[student_marks > np.mean(student_marks)]

array([40, 40, 50, 65])

In [23]:
np.mean(student_marks)

33.888888888888886

In [27]:
student_marks[(student_marks > 20) 

array([30, 40, 30, 40, 50])

In [114]:
arr = np.arange(12)

In [115]:
arr = np.arange(12)
array_3d = arr.reshape(2,3,2)

In [116]:
array_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])